const quizzes = [
  {
    question:
      "What's the best thing to do when you feel overwhelmed by homework?",
    options: [
      "Stay up all night to finish it",
      "Break it into smaller tasks",
      "Ignore it and play games",
      "Copy a friend's work",
    ],
    correctAnswer: 1,
    points: 10,
    explanation: "Breaking work into smaller pieces makes it more manageable!",
  },
  {
    question: "How can you calm down before a big test?",
    options: [
      "Breathe deeply for 1 minute",
      "Drink three energy drinks",
      "Skip breakfast to save time",
      "Cram right until the test starts",
    ],
    correctAnswer: 0,
    points: 10,
    explanation: "Deep breathing activates your relaxation response",
  },
  {
    question: "What's a healthy social media habit?",
    options: [
      "Checking constantly during class",
      "Comparing yourself to influencers",
      "Taking regular digital breaks",
      "Posting when you're feeling angry",
    ],
    correctAnswer: 2,
    points: 15,
    explanation: "Regular breaks help maintain perspective",
  },
  {
    question: "True or False: Online likes determine your worth",
    options: ["True", "False"],
    correctAnswer: 1,
    points: 5,
    explanation: "Your value isn't measured by social media engagement",
  },
  {
    question:
      "What's the best first step when you feel overwhelmed with homework?",
    options: [
      "Panic and cry",
      "Make a prioritized to-do list",
      "Ignore it and play video games",
      "Ask to copy a friend's work",
    ],
    correctAnswer: 1,
    points: 10,
    explanation:
      "Breaking tasks into smaller steps makes them more manageable.",
  },
  {
    question: "Which activity helps reduce stress hormones the most?",
    options: [
      "Deep breathing for 1 minute",
      "Scrolling through social media",
      "Eating a candy bar",
      "Staying up late",
    ],
    correctAnswer: 0,
    points: 10,
    explanation: "Deep breathing activates the body's relaxation response.",
  },
  {
    question: "How often should you take breaks from social media?",
    options: [
      "Never",
      "Every 30-60 minutes",
      "Only on weekends",
      "When your parents tell you to",
    ],
    correctAnswer: 1,
    points: 10,
    explanation: "Regular breaks help maintain healthy perspective.",
  },
  {
    question: "What's the healthiest way to handle anger?",
    options: [
      "Punch a pillow",
      "Take deep breaths and walk away",
      "Yell at whoever made you mad",
      "Post about it online",
    ],
    correctAnswer: 1,
    points: 10,
    explanation: "Cooling down helps you respond rather than react.",
  },
  {
    question: "What's the ideal amount of sleep for a teenager?",
    options: [
      "4-5 hours",
      "6-7 hours",
      "8-10 hours",
      "Whenever you feel tired",
    ],
    correctAnswer: 2,
    points: 10,
    explanation: "Teens need 8-10 hours for proper brain function.",
  },
  {
    question: "What makes a friendship healthy?",
    options: [
      "Never disagreeing",
      "Making fun of each other",
      "Supporting each other's growth",
      "Talking every single day",
    ],
    correctAnswer: 2,
    points: 10,
    explanation: "Good friends encourage your best self.",
  },
  {
    question: "Which is NOT a good self-care activity?",
    options: [
      "Drawing or coloring",
      "Staying in bed all day",
      "Listening to music",
      "Taking a walk",
    ],
    correctAnswer: 1,
    points: 10,
    explanation: "While rest is important, complete isolation isn't healthy.",
  },
  {
    question: "What's a sign you're experiencing too much stress?",
    options: [
      "Laughing with friends",
      "Headaches or stomachaches",
      "Finishing homework early",
      "Helping classmates",
    ],
    correctAnswer: 1,
    points: 10,
    explanation: "Physical symptoms often indicate excessive stress.",
  },
  {
    question:
      "True or False: Everyone's social media posts show their real life",
    options: ["True", "False"],
    correctAnswer: 1,
    points: 10,
    explanation:
      "People usually only share highlights, not everyday struggles.",
  },
  {
    question: "Journaling helps mental health by:",
    options: [
      "Making thoughts more clear",
      "Wasting paper",
      "Taking too much time",
      "Making you overthink",
    ],
    correctAnswer: 0,
    points: 10,
    explanation: "Writing organizes thoughts and reduces overwhelm.",
  },
  {
    question:
      "What's the best first step when you feel overwhelmed with homework?",
    options: [
      "Panic and cry",
      "Make a prioritized to-do list",
      "Ignore it and play video games",
      "Ask to copy a friend's work",
    ],
    correctAnswer: 1,
    points: 10,
    explanation:
      "Breaking tasks into smaller steps makes them more manageable.",
  },
  {
    question: "Which activity helps reduce stress hormones the most?",
    options: [
      "Deep breathing for 1 minute",
      "Scrolling through social media",
      "Eating a candy bar",
      "Staying up late",
    ],
    correctAnswer: 0,
    points: 10,
    explanation: "Deep breathing activates the body's relaxation response.",
  },
  {
    question: "What's a sign you're experiencing too much stress?",
    options: [
      "Laughing with friends",
      "Headaches or stomachaches",
      "Finishing homework early",
      "Helping classmates",
    ],
    correctAnswer: 1,
    points: 10,
    explanation: "Physical symptoms often indicate excessive stress.",
  },
  {
    question: "How often should you take breaks when studying?",
    options: [
      "Every 30 minutes",
      "Every 2 hours",
      "Never - push through!",
      "Only when you feel tired",
    ],
    correctAnswer: 0,
    points: 10,
    explanation: "Short breaks every 30-50 minutes improve focus.",
  },
  {
    question: "What's the healthiest response to a bad grade?",
    options: [
      "Tear up the paper",
      "Ask the teacher how to improve",
      "Hide it from your parents",
      "Assume you're bad at the subject",
    ],
    correctAnswer: 1,
    points: 10,
    explanation: "Using it as a learning opportunity helps growth.",
  },
  {
    question: "Which of these is NOT a healthy coping skill?",
    options: [
      "Drawing or journaling",
      "Taking deep breaths",
      "Binge eating snacks",
      "Talking to a friend",
    ],
    correctAnswer: 2,
    points: 10,
    explanation: "Using food to cope can create unhealthy patterns.",
  },
  {
    question: "True or False: All stress is bad for you.",
    options: ["True", "False"],
    correctAnswer: 1,
    points: 10,
    explanation: "Some stress can motivate you to do your best.",
  },
  {
    question:
      "What's the best thing to do when you can't sleep because of worries?",
    options: [
      "Watch videos until you pass out",
      "Write down your thoughts",
      "Play a loud game",
      "Text friends all night",
    ],
    correctAnswer: 1,
    points: 10,
    explanation: "Writing clears your mind for better sleep.",
  },
  {
    question: "Which habit helps most with morning stress?",
    options: [
      "Hitting snooze 5 times",
      "Preparing your things the night before",
      "Skipping breakfast",
      "Rushing through your routine",
    ],
    correctAnswer: 1,
    points: 10,
    explanation: "Being prepared reduces morning chaos.",
  },
  {
    question: "How can you calm down during a test if you blank?",
    options: [
      "Put your head down and give up",
      "Breathe deeply and reread the question",
      "Keep staring until you remember",
      "Ask to leave the room",
    ],
    correctAnswer: 1,
    points: 10,
    explanation: "Deep breathing helps reset your focus.",
  },
  {
    question: "What's the ideal amount of sleep for a teenager?",
    options: [
      "4-5 hours",
      "6-7 hours",
      "8-10 hours",
      "Whenever you feel tired",
    ],
    correctAnswer: 2,
    points: 10,
    explanation: "Teens need 8-10 hours for proper brain function.",
  },
  {
    question: "How often should you take breaks from social media?",
    options: [
      "Never",
      "Every 30-60 minutes",
      "Only on weekends",
      "When your parents tell you to",
    ],
    correctAnswer: 1,
    points: 10,
    explanation: "Regular breaks help maintain healthy perspective.",
  },
  {
    question:
      "True or False: Everyone's social media posts show their real life",
    options: ["True", "False"],
    correctAnswer: 1,
    points: 10,
    explanation:
      "People usually only share highlights, not everyday struggles.",
  },
  {
    question: "What makes a friendship healthy?",
    options: [
      "Never disagreeing",
      "Making fun of each other",
      "Supporting each other's growth",
      "Talking every single day",
    ],
    correctAnswer: 2,
    points: 10,
    explanation: "Good friends encourage your best self.",
  },
  {
    question: "What's the healthiest way to handle anger?",
    options: [
      "Punch a pillow",
      "Take deep breaths and walk away",
      "Yell at whoever made you mad",
      "Post about it online",
    ],
    correctAnswer: 1,
    points: 10,
    explanation: "Cooling down helps you respond rather than react.",
  },
  {
    question: "Journaling helps mental health by:",
    options: [
      "Making thoughts more clear",
      "Wasting paper",
      "Taking too much time",
      "Making you overthink",
    ],
    correctAnswer: 0,
    points: 10,
    explanation: "Writing organizes thoughts and reduces overwhelm.",
  },
  {
    question: "Which is NOT a good self-care activity?",
    options: [
      "Drawing or coloring",
      "Staying in bed all day",
      "Listening to music",
      "Taking a walk",
    ],
    correctAnswer: 1,
    points: 15,
    explanation: "While rest is important, complete isolation isn't healthy.",
  },
  {
    question: "What's the best response to bullying?",
    options: [
      "Fight back physically",
      "Tell a trusted adult",
      "Ignore it and hope it stops",
      "Bully them back online",
    ],
    correctAnswer: 1,
    points: 15,
    explanation: "Reporting to adults creates the safest solution.",
  },
  {
    question:
      "True or False: Mental health is just as important as physical health",
    options: ["True", "False"],
    correctAnswer: 0,
    points: 15,
    explanation: "Both are equally important for overall wellbeing.",
  },
  {
    question:
      "What should you do if a friend tells you they feel really sad all the time?",
    options: [
      "Tell them to cheer up",
      "Ignore them",
      "Encourage them to talk to a trusted adult",
      "Make fun of them to distract them",
    ],
    correctAnswer: 2,
    points: 10,
    explanation:
      "Encouraging friends to talk to trusted adults helps them get support.",
  },
  {
    question: "Which of these can help improve your mood naturally?",
    options: [
      "Spending time in nature",
      "Skipping meals",
      "Staying up all night",
      "Yelling at people",
    ],
    correctAnswer: 0,
    points: 10,
    explanation: "Nature can have a calming and uplifting effect on your mood.",
  },
  {
    question: "How can you support a friend who is feeling anxious?",
    options: [
      "Tell them to get over it",
      "Avoid them until they feel better",
      "Listen without judgment",
      "Laugh at their fears",
    ],
    correctAnswer: 2,
    points: 10,
    explanation: "Listening without judging builds trust and support.",
  },
  {
    question: "What does it mean to practice gratitude?",
    options: [
      "Feeling jealous of others",
      "Focusing only on what you don’t have",
      "Appreciating the good things in life",
      "Ignoring your feelings",
    ],
    correctAnswer: 2,
    points: 10,
    explanation: "Gratitude helps shift focus to what’s positive.",
  },
  {
    question: "Why is talking about your feelings important?",
    options: [
      "It makes you look weak",
      "It helps you understand and manage emotions",
      "It solves all your problems instantly",
      "It makes people uncomfortable",
    ],
    correctAnswer: 1,
    points: 10,
    explanation: "Expressing emotions helps you cope and gain support.",
  },
  {
    question: "What's a good way to practice mindfulness?",
    options: [
      "Multitasking",
      "Judging your thoughts",
      "Focusing on your breath",
      "Scrolling endlessly online",
    ],
    correctAnswer: 2,
    points: 10,
    explanation: "Mindfulness often begins with focusing on your breath.",
  },
  {
    question: "Which is a sign of good mental health?",
    options: [
      "Never crying",
      "Always being happy",
      "Being able to cope with everyday stress",
      "Never asking for help",
    ],
    correctAnswer: 2,
    points: 10,
    explanation: "Good mental health includes managing stress in healthy ways.",
  },
  {
    question: "What is empathy?",
    options: [
      "Fixing someone’s problems",
      "Feeling sorry for someone",
      "Understanding how others feel",
      "Ignoring other people’s emotions",
    ],
    correctAnswer: 2,
    points: 10,
    explanation:
      "Empathy means trying to understand someone else’s experience.",
  },
  {
    question: "How does exercise affect your mental health?",
    options: [
      "It makes you more anxious",
      "It helps release feel-good chemicals",
      "It only benefits your muscles",
      "It causes stress",
    ],
    correctAnswer: 1,
    points: 10,
    explanation: "Exercise releases endorphins that boost your mood.",
  },
  {
    question: "What is self-compassion?",
    options: [
      "Being selfish",
      "Treating yourself with kindness during hard times",
      "Ignoring your mistakes",
      "Bragging about your success",
    ],
    correctAnswer: 1,
    points: 10,
    explanation:
      "Self-compassion means being kind to yourself, even when things go wrong.",
  },
  {
    question:
      "What should you do if you're feeling hopeless or sad for more than two weeks?",
    options: [
      "Keep it to yourself",
      "Tell a friend only",
      "Seek help from a trusted adult or counselor",
      "Wait and see if it goes away",
    ],
    correctAnswer: 2,
    points: 10,
    explanation:
      "Long-lasting sadness should be discussed with a professional or trusted adult.",
  },
  {
    question: "What is resilience?",
    options: [
      "Never feeling sad",
      "Always being successful",
      "Bouncing back from difficulties",
      "Avoiding all problems",
    ],
    correctAnswer: 2,
    points: 10,
    explanation: "Resilience is the ability to recover after setbacks.",
  },
  {
    question: "How can sleep affect your mental health?",
    options: [
      "It has no effect",
      "Too much sleep makes you feel hyper",
      "Lack of sleep can increase anxiety",
      "Only affects physical energy",
    ],
    correctAnswer: 2,
    points: 10,
    explanation: "Poor sleep can increase stress and anxiety levels.",
  },
  {
    question: "Which of these is a healthy way to deal with sadness?",
    options: [
      "Bottle it up",
      "Express it through talking or writing",
      "Pretend you're fine",
      "Yell at someone",
    ],
    correctAnswer: 1,
    points: 10,
    explanation: "Expressing emotions helps with understanding and healing.",
  },
  {
    question: "What is a benefit of setting boundaries?",
    options: [
      "Losing friends",
      "Getting in trouble",
      "Protecting your mental health",
      "Making people angry",
    ],
    correctAnswer: 2,
    points: 10,
    explanation: "Healthy boundaries help protect your emotional well-being.",
  },
  {
    question: "When is the best time to ask for help with mental health?",
    options: [
      "Only in emergencies",
      "Before things get worse",
      "Never, deal with it alone",
      "After you’ve tried everything else",
    ],
    correctAnswer: 1,
    points: 10,
    explanation: "Early help prevents problems from growing.",
  },
  {
    question: "Which of these shows good emotional awareness?",
    options: [
      "Ignoring how you feel",
      "Screaming when frustrated",
      "Noticing and naming your emotions",
      "Blaming others for your mood",
    ],
    correctAnswer: 2,
    points: 10,
    explanation: "Understanding your emotions is key to managing them.",
  },
  {
    question: "Why might someone use a coping strategy?",
    options: [
      "To avoid dealing with problems",
      "To manage stress or emotions",
      "To become popular",
      "To hide their feelings",
    ],
    correctAnswer: 1,
    points: 10,
    explanation: "Coping strategies help deal with emotional challenges.",
  },
  {
    question: "Which of the following is a healthy way to cope with stress?",
    options: [
      "Deep breathing",
      "Yelling at someone",
      "Ignoring your feelings",
      "Staying up late",
    ],
    correctAnswer: 0,
    points: 10,
    explanation: "Breathing deeply signals your brain to calm down.",
  },
  {
    question: "What does a school counselor do?",
    options: [
      "Give punishments",
      "Only help with class schedules",
      "Support students' academic and emotional needs",
      "Supervise lunch",
    ],
    correctAnswer: 2,
    points: 10,
    explanation: "School counselors support both academic and mental wellness.",
  },
  {
    question: "Which activity can help calm your mind?",
    options: [
      "Watching stressful news",
      "Practicing deep breathing",
      "Arguing with others",
      "Skipping meals",
    ],
    correctAnswer: 1,
    points: 10,
    explanation:
      "Deep breathing activates the relaxation response in your body.",
  },
  {
    question: "Why is journaling helpful for mental health?",
    options: [
      "It wastes time",
      "It helps you avoid problems",
      "It helps you process your thoughts and emotions",
      "It makes you feel worse",
    ],
    correctAnswer: 2,
    points: 10,
    explanation:
      "Journaling helps you better understand and cope with emotions.",
  },
  {
    question: "How can social media negatively affect your mental health?",
    options: [
      "Helping you connect with friends",
      "Creating unrealistic comparisons",
      "Providing support groups",
      "Sharing positive news",
    ],
    correctAnswer: 1,
    points: 10,
    explanation:
      "Comparing yourself to others on social media can harm self-esteem.",
  },
  {
    question: "What should you do if someone is being bullied?",
    options: [
      "Join in",
      "Stay silent",
      "Report it to a trusted adult",
      "Record it to share online",
    ],
    correctAnswer: 2,
    points: 10,
    explanation:
      "Speaking up and getting help is the right way to respond to bullying.",
  },
  {
    question: "What is a panic attack?",
    options: [
      "Being dramatic",
      "An intense wave of fear with physical symptoms",
      "A bad attitude",
      "A stomach ache",
    ],
    correctAnswer: 1,
    points: 10,
    explanation:
      "Panic attacks are sudden and intense with physical and emotional symptoms.",
  },
  {
    question: "Which food choice can support mental well-being?",
    options: [
      "Sugary snacks all day",
      "Skipping breakfast",
      "Balanced meals with fruits and vegetables",
      "Caffeine every hour",
    ],
    correctAnswer: 2,
    points: 10,
    explanation: "Nutritious foods fuel both the body and mind.",
  },
  {
    question: "Why is it important to take breaks during study time?",
    options: [
      "To lose focus",
      "To avoid responsibilities",
      "To recharge your brain and improve focus",
      "To watch more TV",
    ],
    correctAnswer: 2,
    points: 10,
    explanation: "Breaks help your brain reset and retain information better.",
  },
  {
    question: "What is stigma in mental health?",
    options: [
      "Positive attention",
      "Support from friends",
      "Negative labels or stereotypes about mental illness",
      "Medical treatment",
    ],
    correctAnswer: 2,
    points: 10,
    explanation: "Stigma discourages people from seeking help.",
  },
  {
    question: "Which of the following is a calming activity?",
    options: [
      "Taking a walk",
      "Shouting in frustration",
      "Skipping class",
      "Arguing with friends",
    ],
    correctAnswer: 0,
    points: 10,
    explanation: "Walking can reduce stress and clear your mind.",
  },
  {
    question: "How can music affect your mood?",
    options: [
      "Only makes you sleepy",
      "Doesn’t affect mood",
      "Can make you feel better or worse depending on the type",
      "Only works if it’s loud",
    ],
    correctAnswer: 2,
    points: 10,
    explanation: "Music can influence your emotions positively or negatively.",
  },
  {
    question: "What is the first step to managing stress?",
    options: [
      "Ignore it",
      "Recognize what is causing it",
      "Complain to others",
      "Eat junk food",
    ],
    correctAnswer: 1,
    points: 10,
    explanation:
      "Understanding the source of stress helps you manage it better.",
  },
  {
    question: "How does kindness affect mental health?",
    options: [
      "It has no effect",
      "It improves your mood and others’",
      "It only helps others",
      "It makes you tired",
    ],
    correctAnswer: 1,
    points: 10,
    explanation: "Acts of kindness release feel-good chemicals in your brain.",
  },
  {
    question: "What is one way to deal with peer pressure?",
    options: [
      "Do what others say to fit in",
      "Say no and walk away",
      "Lie to avoid conflict",
      "Agree but don’t do it",
    ],
    correctAnswer: 1,
    points: 10,
    explanation:
      "Assertively saying no protects your values and mental health.",
  },
  {
    question: "What can positive self-talk do?",
    options: [
      "Make you overconfident",
      "Reduce stress and boost confidence",
      "Replace the need for help",
      "Prevent emotions",
    ],
    correctAnswer: 1,
    points: 10,
    explanation: "Positive self-talk supports a healthy mindset.",
  },
  {
    question: "What does it mean to ‘check in’ with your feelings?",
    options: [
      "Ignore how you feel",
      "Tell others how they feel",
      "Pause to notice and name your emotions",
      "Try not to cry",
    ],
    correctAnswer: 2,
    points: 10,
    explanation: "Checking in helps you understand and manage your emotions.",
  },
  {
    question: "What is one sign of anxiety?",
    options: [
      "Feeling excited",
      "Constant worry or nervousness",
      "Always being sleepy",
      "Not caring about anything",
    ],
    correctAnswer: 1,
    points: 10,
    explanation: "Anxiety often involves ongoing fear or worry.",
  },
  {
    question: "Which of these is a myth about mental health?",
    options: [
      "Mental health issues are common",
      "Only adults can have mental health problems",
      "Talking helps manage emotions",
      "Support is available for those who ask",
    ],
    correctAnswer: 1,
    points: 10,
    explanation: "Kids and teens can also experience mental health challenges.",
  },
  {
    question: "How can staying organized help your mental health?",
    options: [
      "Makes you more stressed",
      "Helps reduce overwhelm and anxiety",
      "Takes too much time",
      "Makes you obsessive",
    ],
    correctAnswer: 1,
    points: 10,
    explanation: "Organization gives you more control and reduces stress.",
  },
  {
    question: "How do hobbies support mental wellness?",
    options: [
      "They waste time",
      "They distract from responsibilities",
      "They offer joy, relaxation, and creativity",
      "They isolate you",
    ],
    correctAnswer: 2,
    points: 10,
    explanation: "Enjoyable activities improve mood and reduce stress.",
  },
  {
    question: "What does it mean to validate someone’s feelings?",
    options: [
      "Tell them to stop crying",
      "Say their feelings are wrong",
      "Acknowledge their emotions without judgment",
      "Change the topic",
    ],
    correctAnswer: 2,
    points: 10,
    explanation: "Validation helps others feel understood and accepted.",
  },
  {
    question: "What is a safe space?",
    options: [
      "A hiding place",
      "A place where someone feels emotionally supported and accepted",
      "A physical shelter only",
      "A loud, crowded room",
    ],
    correctAnswer: 1,
    points: 10,
    explanation: "Safe spaces allow people to express themselves without fear.",
  },
  {
    question: "Why is laughing good for mental health?",
    options: [
      "It wastes time",
      "It releases stress-reducing hormones",
      "It’s only useful in social settings",
      "It makes others uncomfortable",
    ],
    correctAnswer: 1,
    points: 10,
    explanation: "Laughter lowers stress and improves mood.",
  },
  {
    question: "How can a digital detox help your mind?",
    options: [
      "Makes you miss out",
      "Improves focus and reduces anxiety",
      "Ruins your social life",
      "Makes you bored",
    ],
    correctAnswer: 1,
    points: 10,
    explanation: "Unplugging can refresh your mind and reduce overstimulation.",
  },
  {
    question: "What is a growth mindset?",
    options: [
      "Believing you can improve with effort",
      "Thinking you’re already perfect",
      "Avoiding failure at all costs",
      "Only focusing on your strengths",
    ],
    correctAnswer: 0,
    points: 10,
    explanation: "Growth mindset helps you learn and adapt through challenges.",
  },
  {
    question: "What is the purpose of meditation?",
    options: [
      "To fall asleep",
      "To increase stress",
      "To focus and calm the mind",
      "To avoid responsibilities",
    ],
    correctAnswer: 2,
    points: 10,
    explanation: "Meditation trains attention and reduces stress.",
  },
  {
    question:
      "What can you do if your friend refuses to talk about their mental health?",
    options: [
      "Keep pressuring them",
      "Respect their space and check in later",
      "Tell everyone about it",
      "Ignore them completely",
    ],
    correctAnswer: 1,
    points: 10,
    explanation: "Giving space while showing care builds trust.",
  },
  {
    question: "What is self-care?",
    options: [
      "Being lazy",
      "Putting yourself first no matter what",
      "Taking actions to care for your mental, physical, and emotional health",
      "Only doing fun things",
    ],
    correctAnswer: 2,
    points: 10,
    explanation: "Self-care supports your overall well-being.",
  },
  {
    question: "What is one way to prevent burnout?",
    options: [
      "Taking regular breaks and resting",
      "Working nonstop",
      "Ignoring your feelings",
      "Doing everything alone",
    ],
    correctAnswer: 0,
    points: 10,
    explanation: "Rest prevents exhaustion and promotes mental clarity.",
  },
  {
    question: "Which of these is a healthy sleep habit?",
    options: [
      "Sleeping with your phone in hand",
      "Using screens right before bed",
      "Going to bed at the same time each night",
      "Sleeping 4 hours a night",
    ],
    correctAnswer: 2,
    points: 10,
    explanation:
      "Consistent sleep routines support mental and physical health.",
  },
  {
    question: "Why is connection important for mental health?",
    options: [
      "It causes drama",
      "It’s unnecessary",
      "Supportive relationships help reduce loneliness and stress",
      "It wastes time",
    ],
    correctAnswer: 2,
    points: 10,
    explanation: "Being connected to others supports emotional well-being.",
  },
  {
    question: "What does it mean to seek help?",
    options: [
      "Give up on yourself",
      "Depend on others for everything",
      "Take a brave step to improve your mental health",
      "Only rely on friends",
    ],
    correctAnswer: 2,
    points: 10,
    explanation: "Seeking help is a strong and responsible choice.",
  },
  {
    question: "What does it mean to be emotionally intelligent?",
    options: [
      "Avoid emotions",
      "Control others’ emotions",
      "Recognize, understand, and manage your own emotions",
      "Always stay calm",
    ],
    correctAnswer: 2,
    points: 10,
    explanation:
      "Emotional intelligence improves relationships and decision-making.",
  },
  {
    question: "Which of the following is a healthy way to express anger?",
    options: [
      "Yelling at someone",
      "Bottling it up",
      "Writing in a journal or talking to someone calmly",
      "Breaking things",
    ],
    correctAnswer: 2,
    points: 10,
    explanation:
      "Expressing anger in healthy ways like journaling or calm conversations helps manage emotions safely.",
  },
  {
    question: "Why is gratitude good for mental health?",
    options: [
      "It makes you ignore problems",
      "It helps you appreciate what you have and feel more positive",
      "It makes life perfect",
      "It’s only for holidays",
    ],
    correctAnswer: 1,
    points: 10,
    explanation:
      "Gratitude helps shift focus to the positive and improves emotional well-being.",
  },
  {
    question: "What is an example of mindfulness?",
    options: [
      "Doing homework while watching TV",
      "Thinking about the past",
      "Focusing fully on your breathing or surroundings",
      "Multitasking to save time",
    ],
    correctAnswer: 2,
    points: 10,
    explanation:
      "Mindfulness means being present and aware of the current moment without judgment.",
  },
  {
    question: "What is one way to show empathy?",
    options: [
      "Ignore someone’s feelings",
      "Tell them to get over it",
      "Listen and try to understand how they feel",
      "Change the subject",
    ],
    correctAnswer: 2,
    points: 10,
    explanation:
      "Empathy involves listening and understanding another person's emotions.",
  },
  {
    question: "What is the role of a guidance counselor?",
    options: [
      "Give punishments",
      "Only help with grades",
      "Support students’ emotional, academic, and social needs",
      "Watch students during lunch",
    ],
    correctAnswer: 2,
    points: 10,
    explanation:
      "Guidance counselors help students with mental health, academics, and life skills.",
  },
  {
    question: "How can you support a friend who feels down?",
    options: [
      "Make fun of them to cheer them up",
      "Tell them to snap out of it",
      "Let them know you care and offer to listen",
      "Avoid them until they feel better",
    ],
    correctAnswer: 2,
    points: 10,
    explanation:
      "Offering care and a listening ear helps friends feel supported.",
  },
  {
    question: "Why is asking for help a strength?",
    options: [
      "It shows weakness",
      "It means you can’t handle life",
      "It shows you're weak-minded",
      "It means you're taking care of yourself",
    ],
    correctAnswer: 3,
    points: 10,
    explanation:
      "Asking for help shows self-awareness and strength, not weakness.",
  },
  {
    question: "Which of these is a boundary?",
    options: [
      "Letting others decide for you",
      "Saying no when something makes you uncomfortable",
      "Doing everything for your friends",
      "Ignoring your own needs",
    ],
    correctAnswer: 1,
    points: 10,
    explanation:
      "Healthy boundaries protect your emotional and physical well-being.",
  },
  {
    question: "What’s the best way to start improving your mental health?",
    options: [
      "Wait until it gets worse",
      "Talk to a trusted adult or professional",
      "Ignore your feelings",
      "Isolate yourself",
    ],
    correctAnswer: 1,
    points: 10,
    explanation:
      "Talking to someone you trust is a great first step toward healing.",
  },
  {
    question: "Which is a sign you might need a break?",
    options: [
      "Feeling energized and focused",
      "Having trouble sleeping, concentrating, or feeling overwhelmed",
      "Doing well in school",
      "Laughing with friends",
    ],
    correctAnswer: 1,
    points: 10,
    explanation:
      "Feeling overwhelmed or unfocused can mean you need rest and care.",
  },
  {
    question: "What is resilience?",
    options: [
      "Never having problems",
      "Bouncing back from difficulties or setbacks",
      "Avoiding emotions",
      "Ignoring challenges",
    ],
    correctAnswer: 1,
    points: 10,
    explanation:
      "Resilience is the ability to recover and learn from tough times.",
  },
  {
    question: "How does hydration help mental health?",
    options: [
      "It doesn’t matter",
      "It makes you sleepy",
      "It supports brain function and mood balance",
      "It replaces meals",
    ],
    correctAnswer: 2,
    points: 10,
    explanation:
      "Drinking enough water helps your brain stay sharp and boosts your mood.",
  },
  {
    question: "What is toxic positivity?",
    options: [
      "Being supportive and encouraging",
      "Forcing positivity and ignoring real emotions",
      "Motivating someone kindly",
      "Being helpful and optimistic",
    ],
    correctAnswer: 1,
    points: 10,
    explanation:
      "Toxic positivity ignores valid emotions and can make someone feel worse.",
  },
  {
    question: "How can you reduce test anxiety?",
    options: [
      "Avoid studying",
      "Stay up all night",
      "Prepare ahead, breathe deeply, and take breaks",
      "Keep thinking about failing",
    ],
    correctAnswer: 2,
    points: 10,
    explanation:
      "Being prepared and calm helps reduce anxiety and improve performance.",
  },
  {
    question: "Why is it important to know your triggers?",
    options: [
      "To avoid emotions forever",
      "To blame others",
      "To understand what situations cause stress and plan how to cope",
      "To get more attention",
    ],
    correctAnswer: 2,
    points: 10,
    explanation:
      "Knowing your triggers helps you manage reactions and build coping skills.",
  },
];

module.exports = quizzes;
